import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import AuthContextProvider from "../context/AuthContext";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Quiz App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthContextProvider>{children}</AuthContextProvider>
        <Toaster 
          position="top-center"
          richColors
          expand={true}
        />
      </body>
    </html>
  );
}